# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

#colors for ls

export LS_OPTIONS='--color=auto'
export CLICOLOR='Yes'
export LSCOLORS=' '



# User specific aliases and functions

alias ls='ls --color'
alias home='cd ~'
alias skeletor2='cd ~/www/skeletor-2.0'
alias skeletor1='cd ~/www/skeletor-1.4'
alias qlr='cd ~/www/qlreviews'
alias ql='cd ~/www/quickenloans4'
alias a='cd app/'
alias c='cd controllers/'
alias b='cd ..'




function cdl()
{
cd "$1"
ls "$1"
}

export CVSROOT=':pserver:bnagi@cvsprod:/cvs/web'
