#!/bin/bash
source ~/dotfiles/shell/bash_configs/basic
source ~/dotfiles/git/git-completion.bash
source ~/dotfiles/git/git-prompt.sh
source ~/dotfiles/shell/tf-prompt.sh

# silence zsh bagger message on mac
if [[ "$(uname)" == "Darwin" ]]; then
  export BASH_SILENCE_DEPRECATION_WARNING=1
fi

function webstorm {
  open -na "Webstorm.app" --args "$@"
}

PS1="$PS1\'$(__git_ps1)'\'$(__terraform_ps1)'\[$WHITE\]\$ "
export PATH="$HOME/bin:$HOME/opt:$PATH"
