#!/bin/bash
source ~/dotfiles/bash_configs/basic
source ~/dotfiles/scripts/git-completion.bash
source ~/dotfiles/scripts/git-prompt.sh
source ~/dotfiles/scripts/tf-prompt.sh

function webstorm {
  open -na "Webstorm.app" --args "$@"
}

PS1="$PS1\$(__git_ps1)\$(__terraform_ps1)\[$WHITE\]\$ "
export PATH="$HOME/bin:$HOME/opt:$PATH"
